### ISSUE TITLE
Assignment 4

### ISSUE THREAD

**Issue by dylan-linares-culp** [VIS-2129-F2020/dylanculp-vis#1]
I've submitted my .rmd file for Assignment 4. At the moment, I'm unable to produce an HTML file, due to some combination of internet connection/OSM server issues. I keep getting the following error at line 98 in the knitting process: 

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failed to connect to localhost port 8080: Connection refused
Calls: <Anonymous> ... request_fetch -> request_fetch.write_memory -> <Anonymous>
Execution halted

I've been repeatedly trying to fix this since this morning (each attempt at knitting takes about 20-30 minutes), and will continue working to have the HTML file added as soon as possible.

**Comment by c-voulgaris** [comment]
This is fine. Aleks will grade your Rmd file.
